### PR TITLE
matcracker Ur gae

### PR DESCRIPTION
**Pull request by IcyEndymion004**
Fixes There little issue of being little bitchs <3

test it it adds nothing new accept get poggit to not be gay for it

### CODE REVIEW

**Comment by IcyEndymion004** [comment]
Please Fight me

**Comment by ethaniccc** [comment]
Sure I’ll fight you‼️
What’s “gay” is the fact you screwed up syntax within 3 lines. 
Git gud.

**Comment by IcyEndymion004** [comment]
> Sure I’ll fight you‼️
> What’s “gay” is the fact you screwed up syntax within 3 lines.
> Git gud.

Thx mate for telling me i took 3 seconds on this 
Thx for taking the time out of your day too review this for me Thankyou

**Comment by ethaniccc** [comment]
Yes it takes 1 second for anyone to literally see the mistake, yw 

And wow it’s as if it’s hard to make log calls in 3 seconds - much less 1 !!

**Comment by IcyEndymion004** [comment]
> Yes it takes 1 second for anyone to literally see the mistake, yw
> 
> And wow it’s as if it’s hard to make log calls in 3 seconds - much less 1 !!

: o

**Comment by Aericio** [comment]
going to do something else

**Pull request closed without merging**
